//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_31146
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Test.
    /// </summary>
    // *** Start programmer edit section *** (Test CustomAttributes)

    // *** End programmer edit section *** (Test CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("WebNanny_TestE", new string[] {
            "testint as \'Testint\'",
            "teststring as \'Teststring\'"})]
    [View("WebNanny_TestL", new string[] {
            "testint as \'Testint\'",
            "teststring as \'Teststring\'"})]
    public class Test : ICSSoft.STORMNET.DataObject
    {
        
        private int ftestint;
        
        private string fteststring;
        
        // *** Start programmer edit section *** (Test CustomMembers)

        // *** End programmer edit section *** (Test CustomMembers)

        
        /// <summary>
        /// testint.
        /// </summary>
        // *** Start programmer edit section *** (Test.testint CustomAttributes)

        // *** End programmer edit section *** (Test.testint CustomAttributes)
        public virtual int testint
        {
            get
            {
                // *** Start programmer edit section *** (Test.testint Get start)

                // *** End programmer edit section *** (Test.testint Get start)
                int result = this.ftestint;
                // *** Start programmer edit section *** (Test.testint Get end)

                // *** End programmer edit section *** (Test.testint Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Test.testint Set start)

                // *** End programmer edit section *** (Test.testint Set start)
                this.ftestint = value;
                // *** Start programmer edit section *** (Test.testint Set end)

                // *** End programmer edit section *** (Test.testint Set end)
            }
        }
        
        /// <summary>
        /// teststring.
        /// </summary>
        // *** Start programmer edit section *** (Test.teststring CustomAttributes)

        // *** End programmer edit section *** (Test.teststring CustomAttributes)
        [StrLen(255)]
        public virtual string teststring
        {
            get
            {
                // *** Start programmer edit section *** (Test.teststring Get start)

                // *** End programmer edit section *** (Test.teststring Get start)
                string result = this.fteststring;
                // *** Start programmer edit section *** (Test.teststring Get end)

                // *** End programmer edit section *** (Test.teststring Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Test.teststring Set start)

                // *** End programmer edit section *** (Test.teststring Set start)
                this.fteststring = value;
                // *** Start programmer edit section *** (Test.teststring Set end)

                // *** End programmer edit section *** (Test.teststring Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "WebNanny_TestE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View WebNanny_TestE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("WebNanny_TestE", typeof(IIS.Product_31146.Test));
                }
            }
            
            /// <summary>
            /// "WebNanny_TestL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View WebNanny_TestL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("WebNanny_TestL", typeof(IIS.Product_31146.Test));
                }
            }
        }
    }
}
