/*flexberryautogenerated="true"*/
namespace IIS.Product_31146
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class WebNanny_TestL : BaseListForm<Test>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public WebNanny_TestL() : base(Test.Views.WebNanny_TestL)
        {
            EditPage = WebNanny_TestE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Test/WebNanny_TestL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
